# Generated by Django 5.1.1 on 2024-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('año_inicio', models.DateField()),
                ('año_fin', models.DateField()),
                ('descripcion_curso', models.TextField()),
            ],
        ),
    ]
