# Generated by Django 5.1.1 on 2024-10-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_educacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacion',
            name='año_fin',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='año_inicio',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='descripcion_curso',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='title',
        ),
        migrations.AddField(
            model_name='educacion',
            name='anio_fin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educacion',
            name='anio_inicio',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='educacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educacion',
            name='titulo',
            field=models.CharField(default=2000, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educacion',
            name='institucion',
            field=models.CharField(max_length=255),
        ),
    ]
