# Generated by Django 5.1.1 on 2024-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_educacion_año_fin_remove_educacion_año_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='anio_fin',
            field=models.PositiveIntegerField(default=2004),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
